### ISSUE TITLE
VDesk fails to install if .NET Core 2.0 is installed

### ISSUE THREAD

**Issue by DMcCunney** [eksime/VDesk#35]
I recently downloaded Microsoft's .NET Core 2.0 release.  As I understand it, it's supposed to include the functionality of .NET 4.61.  But your installer checks for 4.61 and fails to install because it doesn't see it, even though it was previously installed.  I'm uninstalling .NET Core and reinstalling .NET 4.62.  I suspect things will work, but this problem is likely to bite other folks.  If .NET Core does include .NET 4.61 functionality, you might want to have your installer check for it, too.

**Comment by eksime** [comment]
I have .Net Core installed alongside .Net 4.6.1 & the installer works for me :(

As far as I understood it, .Net Core is a cross platform subset of .Net & Due to this application integrating with Windows features I do not believe it will build under .Net Core.

I wouldn't expect 4.6 applications to be runnable under the Core runtime; if you can find a link or msdn article or something stating the opposite I'll look into getting it working under .Net Core.
